Improve Parsing Errors
KamilLelonek/yaml-elixir pull request #47
Opened 2021-03-03 23:33 UTC by TylerPachal

This is an attempt to address: https://github.com/KamilLelonek/yaml-elixir/issues/46.

The underlying `yamerl` library returns useful information about the location and nature of Yaml errors.  With this PR we will now copy those into the `YamlElixir.ParsingError`s.

2021-03-03 23:34 UTC, TylerPachal commented on lib/yaml_elixir.ex
> +      {:error, YamlElixir.ParsingError.from_yamerl(error)}
Annotation: According to the `yamerl` documentation it is possible to return multiple errors.  For now lets just take the first one.

2021-03-03 23:35 UTC, TylerPachal commented on lib/yaml_elixir.ex
>        {:error, %YamlElixir.ParsingError{message: "malformed yaml"}}
Annotation: It looks like there are certain inputs which cause `yamerl` to throw a `FunctionClauseError`.  In those cases the best we can do is keep this generic error message.

2021-03-03 23:38 UTC, TylerPachal commented on lib/yaml_elixir/exceptions.ex
> +  end
Annotation: As a safety precaution we have a catch-all clause incase `yamerl` changes and returns something we were not expecting.

2021-03-04 10:33 UTC, KamilLelonek requested changes
The logic looks OK. Some style changes required.

2021-03-04 10:33 UTC, KamilLelonek commented on test/yaml_elixir_test.exs
> +    yaml = "*invalid"
There's no need to introduce this variable here. You can pass it as a string literal directly into the function below.

2021-03-04 10:33 UTC, KamilLelonek commented on lib/yaml_elixir/exceptions.ex
> +  end
Please use mix formatter and Elixir styleguide. Functions have to be separated by an empty line.

2021-03-04 10:33 UTC, KamilLelonek commented on lib/yaml_elixir/exceptions.ex
> +  end
You don't have to use `do...end` block in one-line functions. Please use `do: ...` syntax.

2021-03-04 10:33 UTC, KamilLelonek commented on lib/yaml_elixir/exceptions.ex
> +  end
This will fit in a one-line function. No need to have 5 lines for such a simple thing. Please refactor this.

2021-03-04 14:18 UTC, TylerPachal commented
@KamilLelonek I simplified the functions and ran `mix.format`.  It also formatted some blocks of code which were not related to my changes.

2021-03-04 14:19 UTC, TylerPachal commented on test/yaml_elixir_test.exs
> +    )
Annotation: No logic change here, `mix format` made thee changes.  It also made some other changes.

2021-03-04 16:41 UTC, KamilLelonek commented on lib/yaml_elixir/exceptions.ex
>    end
```suggestion
  def message(%__MODULE__{message: message, line: line, column: column}),
    do: message <> " (line: #{line}, column: #{column})"
```

2021-03-04 16:42 UTC, KamilLelonek approved these changes
Almost fine :)

2021-03-04 16:42 UTC, merged