Adding exception types
KamilLelonek/yaml-elixir pull request #51
Opened 2021-05-20 07:32 UTC by coryodaniel

Adding types for exceptions so consuming libraries can reference them in typespecs.

2021-05-20 07:44 UTC, KamilLelonek requested changes

2021-05-20 07:44 UTC, KamilLelonek commented on lib/yaml_elixir/exceptions.ex
> +  @type t :: %__MODULE__{message: binary}
It's not just a binary. Please use a proper String type instead.

2021-05-20 07:44 UTC, KamilLelonek commented on lib/yaml_elixir/exceptions.ex
> +    column: integer | nil,
Please use parenthesis for the types.

2021-05-20 07:44 UTC, KamilLelonek commented on lib/yaml_elixir/exceptions.ex
> +    type: term | nil,
Are you sure `type` can be `any()`?

2021-05-20 17:16 UTC, coryodaniel commented on lib/yaml_elixir/exceptions.ex
> +    type: term | nil,
Yikes, that was supposed to be atom.

2021-05-20 17:18 UTC, KamilLelonek approved these changes

2021-07-19 17:23 UTC, coryodaniel commented
Is there anything else I need to do to get this released?

2021-07-19 17:31 UTC, merged

2021-07-19 18:45 UTC, KamilLelonek commented
Merged & published.

2021-07-19 21:18 UTC, coryodaniel commented
Awesome, thank you!